### PR TITLE
DSSPP

### PR DESCRIPTION
**Pull request by TarekTaha**
- Merging the branches to simplify future development

### CODE REVIEW

**Comment by TarekTaha** [comment]
@Randa-Almadhoun  I tested it on ROS kinetic and Ubuntu 16.04, can you test on your Ubuntu 14.04 and let me know.

**Comment by Randa-Almadhoun** [comment]
@TarekTaha I had to do minor changes in order to make the coverage heuristics work, 
I modified the includes in the coverage heuristic files (sspp/coverage_.....h), 
I also removed `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11") ` since it generated runtime error (segmentation fault) when I tested the coverage heuristics.

**Comment by TarekTaha** [comment]
@Randa-Almadhoun  I need the c++11 for FCL in ros-kinetic, I added a check in CMakelists that allows us to deal with this issue. Can you do one more check before I merge.

**Review by Randa-Almadhoun — APPROVED** [review]
@TarekTaha  I tested it and it is working fine

**Pull request merged**
